[chipflow]
project_name = "riscv-demo"

[chipflow.steps]
sim     = "riscv_demo.steps.sim:CXXRTLSimStep"
board   = "riscv_demo.steps.board:GlasgowBoardStep"
silicon = "chipflow_lib.steps.silicon:SiliconStep"

[chipflow.silicon]
process  = "ihp_sg13g2"
pad_ring = "pga144"
reset = "sys_rst_n"

[chipflow.top]
soc = "riscv_demo.soc:DemoSoC"
heartbeat = "chipflow_lib:Heartbeat"

[chipflow.silicon.clocks]
default = 'sys_clk'

[chipflow.silicon.pads]
# System
sys_clk   = { type = "clk", loc = "114" }
sys_rst_n = { type = "i", loc = "115" }

[chipflow.silicon.power]
# these will just default to default power pins defined for pga144?
dvss0 = { loc =   "1" }
dvdd0 = { loc =   "9" }
vss0  = { loc =  "17" }
vdd0  = { loc =  "25" }
dvss1 = { loc =  "33" }
dvdd1 = { loc =  "41" }
vss1  = { loc =  "49" }
vdd1  = { loc =  "57" }
dvss2 = { loc =  "65" }
dvdd2 = { loc =  "73" }
vss2  = { loc =  "81" }
vdd2  = { loc =  "89" }
dvss3 = { loc =  "97" }
dvdd3 = { loc = "105" }
vss3  = { loc = "113" }
vdd3  = { loc = "121" }
dvss4 = { loc = "129" }
dvdd4 = { loc = "137" }
