[chipflow]
project_id = 14

[chipflow.steps]
sim     = "riscv_demo.steps.sim:CXXRTLSimStep"
board   = "riscv_demo.steps.board:GlasgowBoardStep"
silicon = "riscv_demo.steps.silicon:IHP130SiliconStep"

[chipflow.silicon]
process  = "ihp_sg13g2"
pad_ring = "pga144"

[chipflow.silicon.pads]

# QSPI flash
flash_clk = { type = "o",  loc = "2" }
flash_csn = { type = "o",  loc = "3" }
flash_d0  = { type = "io",  loc = "4" }
flash_d1  = { type = "io",  loc = "5" }
flash_d2  = { type = "io",  loc = "6" }
flash_d3  = { type = "io",  loc = "7" }

# I2C 0
i2c0_scl = { type = "io", loc = "26" }
i2c0_sda = { type = "io", loc = "27" }

# UART 0
uart0_rx = {type = "i", loc = "78" }
uart0_tx = {type = "o", loc = "79" }

# System
sys_clk   = { type = "clk", loc = "114" }
sys_rst_n = { type = "i",   loc = "115" }
heartbeat = { type = "o",   loc = "118" }

[chipflow.silicon.power]
dvss0 = { loc =   "1" }
dvdd0 = { loc =   "9" }
vss0  = { loc =  "17" }
vdd0  = { loc =  "25" }
dvss1 = { loc =  "33" }
dvdd1 = { loc =  "41" }
vss1  = { loc =  "49" }
vdd1  = { loc =  "57" }
dvss2 = { loc =  "65" }
dvdd2 = { loc =  "73" }
vss2  = { loc =  "81" }
vdd2  = { loc =  "89" }
dvss3 = { loc =  "97" }
dvdd3 = { loc = "105" }
vss3  = { loc = "113" }
vdd3  = { loc = "121" }
dvss4 = { loc = "129" }
dvdd4 = { loc = "137" }
